import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react';

  

export default function Coin() {

    const ROUTER = useRouter()
    const [COIN,SET_COIN] = useState(null)
    useEffect(()=>{
        const {coin} = ROUTER.query;
        SET_COIN(coin)
    },[])

    return (
        <>
            <Head>
                <title>TradeTracker | Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>

                <div className="w3-white w3-margin w3-card w3-round-large w3-padding">
                    {COIN && <p>{COIN.toUpperCase()+'USDT'}</p>}
                </div>

            </main>

        </>
    )
}